# Site settings
title: Fernando Hage
email: fernandohage at gmail.com
description: >- 
  Site do designer e professor Fernando Hage, contendo projetos, imagens, 
  publicações, artigos, contato, projetos especiais e informações sobre o 
  Caixa de Criadores, premiado em economia criativa por apoiar novos criadores 
  de moda e design.
baseurl: ""
disable_disk_cache: true
url: https://fernandohage.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot

# Include the _pages directory for processing
include:
  - _pages

# Internationalization settings
languages: ["pt", "en"]
default_lang: "pt"

# Language-specific settings
pt:
  title: "Fernando Hage"
  description: "Designer e Professor"
  tagline: "Moda, Artes e Cultura"
  
en:
  title: "Fernando Hage"
  description: "Designer and Professor"
  tagline: "Fashion, Arts and Culture"


feed:
  path: /feed.atom

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - fernandohage.weebly.com
  - .venv
  - .vscode/

