# Welcome to Jekyll!
# Site settings
original_title: Fernando Hage
email: contato@fernandohage.com
original_description: >- 
  Site do designer e professor Fernando Hage, contendo projetos, imagens, 
  publicações, artigos, contato, projetos especiais e informações sobre o 
  Caixa de Criadores, premiado em economia criativa por apoiar novos criadores 
  de moda e design.
baseurl: "" 
url: "" 
twitter_username: fernandohage
github_username: fernandohage

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

# Multilingual configuration
languages: ["pt", "en"]
#default_lang: pt
exclude_from_localization: ["javascript", "images", "css", "assets"]


# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - fernandohage.weebly.com
  - "*.py"
  - .venv
  - .vscode/

